[package]
name = "mult_mat"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
itertools = "0.10.1"
rayon = "1.5.1"
num-traits = "0.2.14"
